"""
Fix incorrect logger.error() calls generated by the previous script.
Issues:
  1. logger.error("msg", postgrestError) — error passed as context (2nd arg)
  2. logger.error("msg", {}, status, body) — too many args (4 args)
  3. logger.error("msg", {}, unknownVal) — unknown not assignable to unknown? edge case

Strategy: scan all logger.error calls and normalize to correct 3-arg form.
"""
import re
from pathlib import Path

TARGET_FILES = [
    "app/api/push/send/route.ts",
    "app/api/push/subscribe/route.ts",
    "app/api/reminders/deadlines/route.ts",
    "app/dashboard/projects/[id]/voice-actions.ts",
    "app/dashboard/settings/generate-catalog-action.ts",
    "lib/catalog-search.ts",
    "lib/web-push.ts",
]


def fix_logger_calls(text: str) -> tuple[str, int]:
    count = 0
    lines = text.splitlines(keepends=True)
    new_lines = []
    for line in lines:
        new_line = line
        # Pattern: logger.error("msg", someVar) — 2 args, second is not {}
        # This means the error was placed as context — move it to 3rd arg
        # logger.error("msg", errorVar) -> logger.error("msg", {}, errorVar)
        m = re.search(
            r'logger\.error\((["\`][^"\`]*["\`]),\s*([^{}\n][^,\n]*?)\)',
            line
        )
        if m:
            msg = m.group(1)
            second = m.group(2).strip()
            # second is not {} so it's an error object passed as context
            new_line = line[:m.start()] + f'logger.error({msg}, {{}}, {second})' + line[m.end():]
            count += 1
            new_lines.append(new_line)
            continue

        # Pattern: logger.error("msg", {}, arg1, arg2) — too many args (4)
        m2 = re.search(
            r'logger\.error\((["\`][^"\`]*["\`]),\s*\{\},\s*([^,\n]+),\s*([^\n]+)\)',
            line
        )
        if m2:
            msg = m2.group(1)
            arg1 = m2.group(2).strip()
            arg2 = m2.group(3).strip().rstrip(')')
            # Combine extra args into context object
            new_line = line[:m2.start()] + f'logger.error({msg}, {{ status: {arg1} }}, {arg2})' + line[m2.end():]
            count += 1
            new_lines.append(new_line)
            continue

        new_lines.append(new_line)

    return "".join(new_lines), count


total = 0
for path_str in TARGET_FILES:
    f = Path(path_str)
    if not f.exists():
        print(f"  SKIP (not found): {path_str}")
        continue
    text = f.read_text(encoding="utf-8", errors="ignore")
    new_text, count = fix_logger_calls(text)
    if count > 0:
        f.write_text(new_text, encoding="utf-8")
        print(f"  {count}x fixed: {path_str}")
        total += count
    else:
        print(f"  0   no changes: {path_str}")

print(f"\nTotal fixes: {total}")
