// ═══════════════════════════════════════════════════════════════════
// _ai_actions/pricing-types.ts — Shared types for AI Pricing
// Extracted from pricing.ts for modularity
// ═══════════════════════════════════════════════════════════════════

export interface AiPriceEstimate {
  itemId: string;
  name: string;
  unit: string;         // original unit from DB
  guardedUnit?: string; // unit after Unit Guard 2.0 (may differ, e.g. mb instead of kpl)
  quantity: number;
  currentMaterial: number;
  currentLabor: number;
  suggestedMaterial: number;
  suggestedLabor: number;
  confidence: "high" | "medium" | "low";
  note: string;
  knrCode: string | null;
  knrSource: "official" | "es-synthetic" | "catalog-l1" | null;
  laborNorm: number | null;
  equipmentPrice?: number;   // Task 2: S-category (excavator/crane rental, PLN/jm)
  equipmentNorm?: number;    // Task 2: equipment hours (mh/jm)
  isAmbiguous?: boolean;
  /** Trace — explains how the price was determined (L1/L2/L3 waterfall) */
  trace?: string;
  /** Debug hint for Tryb Własny misses — best catalog candidate that was below threshold */
  catalogHint?: { name: string; score: number } | null;
  /** Top catalog candidates for Manual Match button */
  catalogCandidates?: Array<{ name: string; mat: number; lab: number; score: number }>;
  /** Shadow: raw KNR dictionary norm — never overwrites protected labor_norm */
  suggestedNorm?: number | null;
  /** Source of material price — for UI badge. 'ai-market' = AI rynkowy fallback */
  matSource?: "knr" | "ai-market" | null;
  /**
   * Effective labor hours = norm × qty × cableMod × surfaceMod × globalLaborMod.
   * Stored as labor_hours_total in DB. More accurate than bare norm × qty.
   */
  laborHoursTotal?: number | null;
  /**
   * Regional modifier applied to labor (e.g. 1.20 for Mazowieckie).
   * Kept separate from suggestedLabor so UI can display the final regionalized price.
   * suggestedLabor is always the BASE price; multiply by regionModifier for display.
   */
  regionModifier?: number;
  /**
   * True when this item is a child of an assembly (Zestaw). SAL skips assembly children
   * because their pricing is governed by the parent assembly's logic, not individual floors.
   */
  isAssemblyChild?: boolean;
  /** Set to true when securityAuditLayer forced a price above the engine result. */
  expert_override?: boolean;
  /**
   * True when SemanticInterpreter classified item with low confidence (no action verb found,
   * heavy appliance inferred from noun only). Price is set to safety floor; user should verify.
   */
  isLowConfidence?: boolean;
  /**
   * Human-readable calculation log generated by SemanticInterpreter + securityAuditLayer.
   * Format: "Detected [Intent] + Object. Applied Floor X PLN. Multipliers: Surface × Ceiling × Height."
   */
  calculationLog?: string;
  /**
   * Hard-material context extracted from the user's AI Context / investmentContext.
   * e.g. "żelbet", "beton monolityczny", "silka".
   * securityAuditLayer merges this with item.name to detect hard-surface floors
   * even when the surface keyword is ONLY in the context box, not in the item name.
   * Architecture Mandate v10.1: Context MUST pass through Expert Guardrails.
   */
  hardContext?: string;
  /**
   * Safety notification from Reality Check Rule 3 (Safety Integrity).
   * Set when item is a high-power device (indukcja/pompa/EV/sauna).
   * UI reads this to display a silent expert notification prompting the user
   * to ensure RCD + MCB protection materials are included in the bill.
   */
  safetyNote?: string;
}

export interface AiPriceResult {
  success: boolean;
  estimates?: AiPriceEstimate[];
  error?: string;
  /** Machine-readable error code for caller logic (e.g. MISSING_RATE → prompt user to set rate) */
  errorCode?: "MISSING_RATE";
}
