-- ═══════════════════════════════════════════════════════════════════
-- Zestaw Engine v2 — gating columns (radical OFF mode)
--
-- Smart Mapping Engine previously auto-expanded any item whose name
-- matched regex triggers (Układanie/Montaż/Trasa…) into a "Zestaw" with
-- virtual children including bruzdowanie. This produced wrong totals on
-- items like "Układanie kabla YKY" (no chase needed) and noise on
-- "Montaż łączników" (BIALY_MONTAZ template has 1 identical child).
--
-- Phase A introduces explicit per-project + per-item gating:
--   • projects.auto_detect_zestawy   — opt-in flag for SCM auto-expansion
--   • project_items.is_quick_estimate — Quick-Estimate-generated rows are
--                                       never re-expanded (already complete)
--
-- Default for existing rows: auto_detect_zestawy = FALSE for ALL projects.
-- This is the radical mode chosen by the Technical Director — no project
-- silently wraps items into Zestawy until the user explicitly opts in.
-- ═══════════════════════════════════════════════════════════════════

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS auto_detect_zestawy boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN projects.auto_detect_zestawy IS
  'When TRUE, Smart Mapping Engine virtually expands matching items into Zestaw assemblies (parent + children with bruzdowanie/cable/box) in PDF, ProjectSummary, and offer routes. Default FALSE (Zestaw Engine v2, 2026-05-04) — explicit opt-in per project to prevent surprise totals. Manual recipes via addZestawToProject still work regardless of this flag.';

ALTER TABLE project_items
  ADD COLUMN IF NOT EXISTS is_quick_estimate boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN project_items.is_quick_estimate IS
  'When TRUE, this row was generated by the Quick Estimate Wizard and must NEVER be auto-expanded by Smart Mapping Engine — it is already a complete deterministic estimate. Set by createQuickEstimateProject. (Zestaw Engine v2, 2026-05-04)';

-- Optional ergonomic index: gating filter is read on every PDF/Summary render
CREATE INDEX IF NOT EXISTS idx_project_items_is_quick_estimate
  ON project_items (project_id) WHERE is_quick_estimate = true;
