export {
  MASTER_IDENTITY,
  IRON_RULE_SPLIT_PRICING,
  IRON_RULE_VAT,
  IRON_RULE_REGION,
  IRON_RULE_DEMO,
  IRON_RULE_KNR_HIERARCHY,
  IRON_RULE_ZESTAWY_360,
  FOUR_IRON_RULES,
} from "./identity-prompts";

export { PRICING_PROMPT, ESTIMATOR_PROMPT, AUDITOR_PROMPT } from "./pricing-prompts";

export {
  GENERATOR_PROMPT,
  ASSEMBLIES_PROMPT,
  IMPORTER_PROMPT,
  QUICK_ESTIMATE_PROMPT,
} from "./knr-prompts";

export {
  SCHEMAT_PROMPT,
  SWITCHBOARD_PROMPT,
  CREATOR_PROMPT,
  AUTOMATION_PROMPT,
  CATALOG_PROMPT,
} from "./panel-audit-prompts";
